title: 'Topology in condensed matter: tying quantum knots'
author: Topology course team
copyright: "2021, TU Delft, CC-BY-SA 4.0 (materials) & BSD (code)"
logo: "logo_small.jpg"
exclude_patterns:
  - _build
  - src  # Obsolete, should eventually be wiped
  - "**.ipynb_checkpoints"
  - readme.md
only_build_toc_files: true
execute:
  execute_notebooks: cache
  timeout: -1
  stderr_output: remove-warn
sphinx:
  config:
    ogp_site_url: "https://topocondmat.org"
    ogp_image: "https://topocondmat.org/_static/logo_small.jpg"
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    - - https://cdn.bokeh.org/bokeh/release/bokeh-2.2.3.min.js
      - crossorigin: anonymous
    - - https://cdn.bokeh.org/bokeh/release/bokeh-widgets-2.2.3.min.js
      - crossorigin: anonymous
    - - https://cdn.bokeh.org/bokeh/release/bokeh-tables-2.2.3.min.js
      - crossorigin: anonymous
    - - https://unpkg.com/@holoviz/panel@0.10.2/dist/panel.min.js
      - crossorigin: anonymous
  local_extensions:
    extensions: ./sphinxext/
  extra_extensions:
    - sphinxext.opengraph
launch_buttons:
  notebook_interface: classic
html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
repository:
  url: https://github.com/topocm/topocm_content
